<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mixed PHP and HTML</title>
</head>
<body>

<h1>Welcome to My Website</h1>

<?php
echo "<p>This is a message generated by PHP!</p>";
?>

<p>This is static HTML content.</p>

</body>
</html>
